---
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  code_blocks: false
  # Number of spaces for each hard tab
  spaces_per_tab: 4

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 1000
  # Number of characters for headings
  heading_line_length: 500
  # Number of characters for code blocks
  code_block_line_length: 1000
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: false
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
